"""AI conversation, message, run, and patch proposal persistence."""

from __future__ import annotations
import json
import sqlite3
from pathlib import Path
from typing import Any, Mapping
from .storage_common import (
    StressSetupSlotConflict,
    _UNSET,
    _json,
    _merge_json_objects,
    _process_is_alive,
    utc_now,
)

class _AiStorageMixin:
    def reconcile_interrupted_ai_state(self) -> None:
        """Close AI and stress state left in-flight by a previous process."""

        stamp = utc_now()
        with self.atomic():
            self.connection.execute(
                """UPDATE ai_messages SET status='interrupted',completed_at=?
                   WHERE status IN ('pending','streaming')""",
                (stamp,),
            )
            self.connection.execute(
                """UPDATE ai_runs SET status='interrupted',completed_at=?
                   WHERE status IN ('pending','running')
                     AND kind<>'stress_setup'""",
                (stamp,),
            )
            setup_rows = self.query(
                """SELECT id,preparation_meta_json FROM ai_runs
                   WHERE kind='stress_setup' AND status='running'"""
            )
            for row in setup_rows:
                try:
                    metadata = json.loads(str(row["preparation_meta_json"] or "{}"))
                except (TypeError, ValueError, json.JSONDecodeError):
                    metadata = {}
                owner_pid = metadata.get("owner_pid") if isinstance(metadata, Mapping) else None
                if _process_is_alive(owner_pid):
                    continue
                self.connection.execute(
                    """UPDATE ai_runs SET status='interrupted',completed_at=?
                       WHERE id=? AND status='running'""",
                    (stamp, str(row["id"])),
                )
            self._reconcile_interrupted_stress_state(stamp)

    def get_or_create_ai_conversation(
        self,
        conversation_id: str,
        attempt_id: int,
        platform: str,
        problem_id: str,
    ) -> tuple[sqlite3.Row, bool]:
        """Return the active conversation for an attempt or create it.

        ``conversation_id`` is generated by the caller so API/SSE code can
        publish a stable identifier before any model request begins.
        """

        attempt = self.connection.execute(
            "SELECT platform,problem_id,active FROM attempts WHERE id=?",
            (attempt_id,),
        ).fetchone()
        if attempt is None:
            raise KeyError(f"attempt {attempt_id} not found")
        platform = str(platform).strip().lower()
        problem_id = str(problem_id).strip()
        if attempt["platform"] != platform or attempt["problem_id"] != problem_id:
            raise ValueError("conversation problem does not match its attempt")
        if not int(attempt["active"]):
            raise ValueError("cannot create a conversation for a closed attempt")

        existing = self.active_ai_conversation(attempt_id)
        if existing is not None:
            return existing, False
        now = utc_now()
        try:
            self.connection.execute(
                """INSERT INTO ai_conversations(
                       id,attempt_id,platform,problem_id,status,created_at,updated_at)
                   VALUES(?,?,?,?,'active',?,?)""",
                (str(conversation_id), attempt_id, platform, problem_id, now, now),
            )
        except sqlite3.IntegrityError:
            # A concurrent creator may have won the partial unique index.
            existing = self.active_ai_conversation(attempt_id)
            if existing is None:
                raise
            return existing, False
        row = self.ai_conversation(str(conversation_id))
        assert row is not None
        return row, True

    def ai_conversation(self, conversation_id: str) -> sqlite3.Row | None:
        return self.connection.execute(
            "SELECT * FROM ai_conversations WHERE id=?", (str(conversation_id),)
        ).fetchone()

    def active_ai_conversation(self, attempt_id: int) -> sqlite3.Row | None:
        return self.connection.execute(
            """SELECT * FROM ai_conversations
               WHERE attempt_id=? AND status='active' LIMIT 1""",
            (attempt_id,),
        ).fetchone()

    def close_ai_conversation(
        self,
        conversation_id: str,
        *,
        closed_at: str | None = None,
        closed_reason: str = "attempt_closed",
        superseded_by: str | None = None,
    ) -> bool:
        if closed_reason not in {"user_cleared", "attempt_closed", "legacy"}:
            raise ValueError("invalid AI conversation closed reason")
        stamp = closed_at or utc_now()
        cursor = self.connection.execute(
            """UPDATE ai_conversations
               SET status='closed',closed_at=?,updated_at=?,closed_reason=?,superseded_by=?
               WHERE id=? AND status='active'""",
            (
                stamp,
                stamp,
                closed_reason,
                str(superseded_by) if superseded_by is not None else None,
                str(conversation_id),
            ),
        )
        return bool(cursor.rowcount)

    def link_ai_conversation_replacement(
        self, conversation_id: str, superseded_by: str
    ) -> sqlite3.Row:
        """Link an archived conversation after its replacement has been created."""

        cursor = self.connection.execute(
            """UPDATE ai_conversations SET superseded_by=?,updated_at=?
               WHERE id=? AND status='closed' AND closed_reason='user_cleared'""",
            (str(superseded_by), utc_now(), str(conversation_id)),
        )
        if cursor.rowcount != 1:
            raise KeyError(f"cleared AI conversation {conversation_id!r} not found")
        row = self.ai_conversation(str(conversation_id))
        assert row is not None
        return row

    def latest_summary_ai_conversation(self, attempt_id: int) -> sqlite3.Row | None:
        """Return the latest conversation eligible for Markdown summarisation.

        A user-cleared conversation remains available for hint/audit queries but
        is deliberately excluded from outbound summary context.
        """

        return self.connection.execute(
            """SELECT * FROM ai_conversations
               WHERE attempt_id=? AND COALESCE(closed_reason,'')!='user_cleared'
               ORDER BY updated_at DESC,rowid DESC LIMIT 1""",
            (int(attempt_id),),
        ).fetchone()

    def create_ai_message(
        self,
        message_id: str,
        conversation_id: str,
        *,
        role: str,
        content: str = "",
        mode: str | None = None,
        hint_level: int = 0,
        status: str = "pending",
        model: str | None = None,
        usage: Mapping[str, Any] | None = None,
        created_at: str | None = None,
    ) -> sqlite3.Row:
        stamp = created_at or utc_now()
        self.connection.execute(
            """INSERT INTO ai_messages(
                   id,conversation_id,role,mode,hint_level,content,status,model,
                   usage_json,created_at)
               VALUES(?,?,?,?,?,?,?,?,?,?)""",
            (
                str(message_id),
                str(conversation_id),
                role,
                mode,
                int(hint_level),
                content,
                status,
                model,
                _json(usage or {}),
                stamp,
            ),
        )
        self.connection.execute(
            "UPDATE ai_conversations SET updated_at=? WHERE id=?",
            (stamp, str(conversation_id)),
        )
        row = self.ai_message(str(message_id))
        assert row is not None
        return row

    def update_ai_message(
        self,
        message_id: str,
        *,
        content: str | object = _UNSET,
        status: str | object = _UNSET,
        model: str | None | object = _UNSET,
        usage: Mapping[str, Any] | object = _UNSET,
        completed_at: str | None | object = _UNSET,
    ) -> sqlite3.Row:
        assignments: list[str] = []
        values: list[Any] = []
        for column, value in (
            ("content", content),
            ("status", status),
            ("model", model),
            ("completed_at", completed_at),
        ):
            if value is not _UNSET:
                assignments.append(f"{column}=?")
                values.append(value)
        if usage is not _UNSET:
            assignments.append("usage_json=?")
            values.append(_json(usage))
        if not assignments:
            row = self.ai_message(str(message_id))
            if row is None:
                raise KeyError(f"AI message {message_id!r} not found")
            return row
        values.append(str(message_id))
        cursor = self.connection.execute(
            f"UPDATE ai_messages SET {','.join(assignments)} WHERE id=?", values
        )
        if cursor.rowcount != 1:
            raise KeyError(f"AI message {message_id!r} not found")
        row = self.ai_message(str(message_id))
        assert row is not None
        self.connection.execute(
            "UPDATE ai_conversations SET updated_at=? WHERE id=?",
            (utc_now(), row["conversation_id"]),
        )
        return row

    def ai_message(self, message_id: str) -> sqlite3.Row | None:
        return self.connection.execute(
            "SELECT * FROM ai_messages WHERE id=?", (str(message_id),)
        ).fetchone()

    def ai_messages(
        self, conversation_id: str, *, limit: int | None = 24
    ) -> list[sqlite3.Row]:
        if limit is None:
            return self.query(
                """SELECT * FROM ai_messages WHERE conversation_id=?
                   ORDER BY created_at,rowid""",
                (str(conversation_id),),
            )
        return self.query(
            """SELECT * FROM ai_messages
               WHERE rowid IN (
                   SELECT rowid FROM ai_messages WHERE conversation_id=?
                   ORDER BY created_at DESC,rowid DESC LIMIT ?
               ) ORDER BY created_at,rowid""",
            (str(conversation_id), max(0, int(limit))),
        )

    def max_ai_hint_level(self, attempt_id: int) -> int:
        row = self.connection.execute(
            """SELECT COALESCE(MAX(m.hint_level),0) AS hint_level
               FROM ai_messages m
               JOIN ai_conversations c ON c.id=m.conversation_id
               WHERE c.attempt_id=? AND m.role='assistant'
                 AND m.status IN ('streaming','complete','interrupted')
                """,
            (attempt_id,),
        ).fetchone()
        return int(row["hint_level"] if row else 0)

    def create_ai_run(
        self,
        run_id: str,
        *,
        kind: str,
        model: str,
        request_summary: Mapping[str, Any] | None = None,
        status: str = "pending",
        conversation_id: str | None = None,
        message_id: str | None = None,
        preparation_meta: Mapping[str, Any] | None = None,
        created_at: str | None = None,
    ) -> sqlite3.Row:
        try:
            self.connection.execute(
                """INSERT INTO ai_runs(
                       id,kind,model,conversation_id,message_id,
                       request_summary_json,status,preparation_meta_json,created_at)
                   VALUES(?,?,?,?,?,?,?,?,?)""",
                (
                    str(run_id),
                    kind,
                    model,
                    conversation_id,
                    message_id,
                    _json(request_summary or {}),
                    status,
                    _json(preparation_meta or {}),
                    created_at or utc_now(),
                ),
            )
        except sqlite3.IntegrityError as exc:
            constraint = getattr(exc, "sqlite_errorcode", None)
            if (
                str(kind) == "stress_setup"
                and str(status) == "running"
                and constraint
                in {
                    sqlite3.SQLITE_CONSTRAINT_PRIMARYKEY,
                    sqlite3.SQLITE_CONSTRAINT_UNIQUE,
                }
            ):
                active = self.active_stress_setup_run()
                if active is not None:
                    raise StressSetupSlotConflict(
                        str(run_id), str(active["id"])
                    ) from None
            raise
        row = self.ai_run(str(run_id))
        assert row is not None
        return row

    def update_ai_run(
        self,
        run_id: str,
        *,
        status: str | object = _UNSET,
        finish_reason: str | None | object = _UNSET,
        usage: Mapping[str, Any] | object = _UNSET,
        error: Mapping[str, Any] | object = _UNSET,
        preparation_meta: Mapping[str, Any] | object = _UNSET,
        completed_at: str | None | object = _UNSET,
    ) -> sqlite3.Row:
        assignments: list[str] = []
        values: list[Any] = []
        for column, value in (
            ("status", status),
            ("finish_reason", finish_reason),
            ("completed_at", completed_at),
        ):
            if value is not _UNSET:
                assignments.append(f"{column}=?")
                values.append(value)
        if usage is not _UNSET:
            assignments.append("usage_json=?")
            values.append(_json(usage))
        if error is not _UNSET:
            assignments.append("error_json=?")
            values.append(_json(error))
        if preparation_meta is not _UNSET and not isinstance(
            preparation_meta, Mapping
        ):
            raise TypeError("preparation_meta must be a mapping")
        if not assignments:
            if preparation_meta is not _UNSET:
                return self.merge_ai_run_preparation_meta(
                    str(run_id), preparation_meta
                )
            row = self.ai_run(str(run_id))
            if row is None:
                raise KeyError(f"AI run {run_id!r} not found")
            return row
        with self.atomic():
            if preparation_meta is not _UNSET:
                current = self.ai_run(str(run_id))
                if current is None:
                    raise KeyError(f"AI run {run_id!r} not found")
                assignments.append("preparation_meta_json=?")
                values.append(
                    _json(
                        _merge_json_objects(
                            current["preparation_meta_json"], preparation_meta
                        )
                    )
                )
            values.append(str(run_id))
            cursor = self.connection.execute(
                f"UPDATE ai_runs SET {','.join(assignments)} WHERE id=?", values
            )
            if cursor.rowcount != 1:
                raise KeyError(f"AI run {run_id!r} not found")
        row = self.ai_run(str(run_id))
        assert row is not None
        return row

    def merge_ai_run_preparation_meta(
        self, run_id: str, updates: Mapping[str, Any]
    ) -> sqlite3.Row:
        """Deep-merge durable preparation timings/cache/failure metadata."""

        if not isinstance(updates, Mapping):
            raise TypeError("updates must be a mapping")
        with self.atomic():
            row = self.ai_run(str(run_id))
            if row is None:
                raise KeyError(f"AI run {run_id!r} not found")
            merged = _merge_json_objects(row["preparation_meta_json"], updates)
            self.connection.execute(
                "UPDATE ai_runs SET preparation_meta_json=? WHERE id=?",
                (_json(merged), str(run_id)),
            )
        updated = self.ai_run(str(run_id))
        assert updated is not None
        return updated

    def ai_run(self, run_id: str) -> sqlite3.Row | None:
        return self.connection.execute(
            "SELECT * FROM ai_runs WHERE id=?", (str(run_id),)
        ).fetchone()

    def create_ai_patch_proposal(
        self,
        proposal_id: str,
        *,
        platform: str,
        problem_id: str,
        source_path: str | Path,
        baseline_hash: str,
        candidate_code: str,
        diff_text: str,
        diagnosis: str = "",
        run_id: str | None = None,
        conversation_id: str | None = None,
        attempt_id: int | None = None,
        created_at: str | None = None,
    ) -> sqlite3.Row:
        self.upsert_problem({"platform": platform, "problem_id": problem_id})
        stamp = created_at or utc_now()
        self.connection.execute(
            """INSERT INTO ai_patch_proposals(
                   id,run_id,conversation_id,attempt_id,platform,problem_id,
                   source_path,baseline_hash,candidate_code,diff_text,diagnosis,
                   status,created_at,updated_at)
               VALUES(?,?,?,?,?,?,?,?,?,?,?,'preview',?,?)""",
            (
                str(proposal_id),
                run_id,
                conversation_id,
                attempt_id,
                platform,
                str(problem_id),
                str(source_path),
                baseline_hash,
                candidate_code,
                diff_text,
                diagnosis,
                stamp,
                stamp,
            ),
        )
        row = self.ai_patch_proposal(str(proposal_id))
        assert row is not None
        return row

    def ai_patch_proposal(self, proposal_id: str) -> sqlite3.Row | None:
        return self.connection.execute(
            "SELECT * FROM ai_patch_proposals WHERE id=?", (str(proposal_id),)
        ).fetchone()

    def update_ai_patch_proposal(
        self,
        proposal_id: str,
        *,
        status: str | object = _UNSET,
        applied_hash: str | None | object = _UNSET,
        backup_path: str | Path | None | object = _UNSET,
        verify: Mapping[str, Any] | object = _UNSET,
        applied_at: str | None | object = _UNSET,
        reverted_at: str | None | object = _UNSET,
    ) -> sqlite3.Row:
        assignments = ["updated_at=?"]
        values: list[Any] = [utc_now()]
        for column, value in (
            ("status", status),
            ("applied_hash", applied_hash),
            ("backup_path", backup_path),
            ("applied_at", applied_at),
            ("reverted_at", reverted_at),
        ):
            if value is not _UNSET:
                assignments.append(f"{column}=?")
                values.append(
                    str(value)
                    if column == "backup_path" and value is not None
                    else value
                )
        if verify is not _UNSET:
            assignments.append("verify_json=?")
            values.append(_json(verify))
        values.append(str(proposal_id))
        cursor = self.connection.execute(
            f"UPDATE ai_patch_proposals SET {','.join(assignments)} WHERE id=?", values
        )
        if cursor.rowcount != 1:
            raise KeyError(f"AI patch proposal {proposal_id!r} not found")
        row = self.ai_patch_proposal(str(proposal_id))
        assert row is not None
        return row
